---
  - name: If installed, remove the epel-release version of npm
    package: name=nodejs state=absent
  - name: If installed, remove the epel-release version of nodejs
    package: name=nodejs state=absent

  - name: Get NVM 0.33.11 install script nvm_install.sh
    get_url:
      url: https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh
      dest: ~/nvm_install.sh
      checksum: sha1:75c00c4458b9067277b06043f0251f8324bf149c

  - name: Make the script file executable
    file:
      path: ~/nvm_install.sh
      mode: 0700

  - name: run NVM install script
    command: ~/nvm_install.sh
    register: result

  #Since the NVM install is just a script, have it output to screen
  - debug:
      msg: " nvm_install.sh output: {{ result.stdout }} "

  #TODO: Replace node version number with variable
  - name: Install Node.js
    shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node {{ node_version }}'
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
      chdir: "{{ ansible_env.HOME }}"
      executable: /bin/bash
